version: '2'
services:
    ramhacks2016-app:
        image: ramhacks2016
        external_links:
            - ramhacks2016-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ramhacks2016?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ramhacks2016-mysql:
        extends:
            file: mysql.yml
            service: ramhacks2016-mysql
