version: '2'
services:
    ramhacks2016-mysql:
        container_name: ramhacks2016-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/ramhacks2016/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=ramhacks2016
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
